language: dart
sudo: false
services:
  - xvfb
dart:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
with_content_shell: false
script:
  - set -e
  - pub run tool/reformat.dart
  - dartanalyzer --fatal-infos --fatal-warnings ./
  - pub run test test/kt_dart_test.dart
  - pub publish -n
  # run coverage with dart 2.2.0 only, it's broken on later versions https://github.com/dart-lang/coverage/issues/249
  - if $(pub --version | grep -q '2.2.0'); then ./tool/run_coverage_locally.sh; fi
after_success:
  # run coverage report only on dart 2.2.0
  - if $(pub --version | grep -q '2.2.0'); then bash <(curl -s https://codecov.io/bash); fi