language: dart
sudo: false
services:
  - xvfb
dart:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
with_content_shell: false
script:
  - set -e
  - pub run tool/reformat.dart
  - dartanalyzer --fatal-infos --fatal-warnings ./
  - pub run test test/kt_dart_test.dart
  - pub publish -n
  - ./tool/run_coverage_locally.sh
after_success:
  # report code coverage only on a single node of the matrix. (prefer latest)
  - if $(pub --version | grep -q '2.4.0'); then bash <(curl -s https://codecov.io/bash); fi