analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - test/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - cancel_subscriptions
    - hash_and_equals
    - directives_ordering
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - sort_constructors_first
    - test_types_in_equals
    - unnecessary_brace_in_string_interps
    - unnecessary_lambdas
    - unnecessary_this
    - unrelated_type_equality_checks
    - valid_regexps
    - prefer_conditional_assignment
    - prefer_interpolation_to_compose_strings
