include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # not everything is documented yet
    public_member_api_docs: false

    # Not supported with Dart 2.2
    prefer_collection_literals: false
    prefer_spread_collections: false