name: kotlin_dart
description: This project is a port of kotlin-stdlib for Dart/Flutter projects. It includes collections (KtList, KtMap, KtSet) with 150+ methods as well as other useful packages.
version: 0.4.1
homepage: https://github.com/passsy/kotlin.dart
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
