name: dart_kollection
description: Brings Kotlins colletions (List, Set, Map) to Dart. Unlike Darts collections kollections are immutable by default but offer special `Mutable` types.
version: 0.3.1
homepage: https://github.com/passsy/dart_kollection
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
