name: dart_kollection
description: Kotlin colletions port to Dart
version: 0.1.0
homepage: https://github.com/passsy/dart_kollection
author: Pascal Welsch <pascal.welsch@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
