name: Analyze

on: [push, pull_request]

jobs:
  analyze:
    timeout-minutes: 5
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        version: ["2.12", "dev"]

    container:
      image: google/dart:${{ matrix.version }}
    
    steps:
    - uses: actions/checkout@master
    - run: pub get
    - run: pub run tool/reformat.dart
    - run: dart format --set-exit-if-changed .
    - run: pub publish -n