name: Analyze

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        version: ["2.6", "2.7", "dev"]

    container:
      image: google/dart:${{ matrix.version }}
    
    steps:
    - uses: actions/checkout@master
    - run: pub get
    - run: pub run tool/reformat.dart
    - run: dartanalyzer --fatal-infos --fatal-warnings .
    - run: pub publish -n
      if: matrix.version != '2.6'